---
title: "Metabolomics Loreal"
output: html_document
date: "2024-09-25"
author: "Britta De Pessemier, adapted by Yang Chen"
---

```{r packages, message=FALSE, warning=FALSE}
# Load Required Libraries
# Data Manipulation
library(tidyverse)
library(dplyr)
library(stringr)
library(tibble)

# Statistical Analysis
library(vegan)
library(rstatix)
library(lmerTest)
library(caret)

# Visualization
library(ggplot2)
library(ggpubr)
library(cowplot)
library(RColorBrewer)
library(svglite)

# Specialized Tools
library(mixOmics)
library(UpSetR)
library(homologueDiscoverer) # devtools::install_github("kevinmildau/homologueDiscoverer")
library(MassTools)           # devtools::install_github("mjhelf/MassTools")
```


```{r}
# Import metabolomics run 3 files
feature_table <- read_csv("../Data/metabolomics/Run3_10252024/FBMN_mgf_Lami_10252024_quant.csv")

#metadata <- read_csv("../Metadata/metadata_final_18062024.csv")
metadata <- read_csv("../Metadata/metadata_Tyler_reordered.csv")

sample_order <- read.csv("../Data/metabolomics/Run3_10252024/Sequence_order_10262024.csv")
#with suspects
annotations <- read.delim("../Data/metabolomics/Run3_10252024/merged_results_with_gnps.tsv")
#without suspects
#annotations <- read.delim("../Data/metabolomics/Run3_10252024/merged_results_with_gnps_withoutsuspects.tsv")
annotations$X.Scan. <- as.character(annotations$X.Scan.)
canopus <- read_tsv("../Data/metabolomics/Run3_10252024/canopus_structure_summary.tsv")
canopus$featureId <- as.character(canopus$featureId)

mapping_file <- read.csv("../Data/metabolomics/Run3_10252024/Mapping_10262024.csv")
```
```{r}
#Function for homologue analysis
plotAnnotatedStatic <- function(annotated, legend_setting = "bottom"){
  
  annotated <- mutate(annotated,
                      homologue_id = if_else(is.na(homologue_id), 0L, homologue_id),
                      homologue_id = as.factor(homologue_id))
  colourCount = length(unique(annotated$homologue_id))
  getPalette = colorRampPalette(RColorBrewer::brewer.pal(9, "Set1"))
  ncolor = length(unique(annotated$homologue_id))
  annotated <- arrange(annotated, desc(homologue_id))
  g <- ggplot(annotated, aes(group = homologue_id)) +
    geom_point(aes(x = rt, y = mz, color = homologue_id, size = homologue_id,
                   shape = homologue_id, alpha = homologue_id)) +
    geom_line(data = filter(annotated, homologue_id != 0),
              aes(x = rt, y = mz, group = homologue_id), alpha = 0.4, linewidth = 0.1) +
    ggtitle("Annotated Peak Table") +
    scale_colour_manual(values = c("black", getPalette(colourCount-1))) +
    scale_alpha_manual(values =  c(0.2, rep(0.85, times = ncolor))) +
    scale_size_manual(values = c(0.1, rep(1.5, times = ncolor))) +
    scale_shape_manual(values = c(1, rep(19, times = ncolor))) +
    xlab("Retention Time (s)") +
    ylab("Mass to Charge Ratio") +
    theme(legend.position=legend_setting, text = element_text(family="mono"))
  return(g)
  
}
```


```{r}
# Find duplicate sample names in the metadata
# Create a subset of rows in the metadata where sample_name appears more than once
duplicates_in_metadata <- metadata[metadata$sample_name %in% metadata$sample_name[duplicated(metadata$sample_name)], ]

# Replace underscores with periods in the mapping_file$Manifest_ID_Sample_Name column
mapping_file$Manifest_ID_Sample_Name <- gsub("_", ".", mapping_file$Manifest_ID_Sample_Name)

# Merge metadata with mapping_file based on sample_name
# Ensure sample_name in metadata matches Manifest_ID_Sample_Name in mapping_file
metadata_2 <- metadata %>% left_join(mapping_file, by = c("sample_name" = "Manifest_ID_Sample_Name"))

# Add a new column SampleID to metadata_2 using Filename_ID
metadata_2$SampleID <- metadata_2$Filename_ID

# Identify duplicate sample names in the updated metadata_2
duplicates_in_metadata <- metadata_2[metadata_2$sample_name %in% metadata_2$sample_name[duplicated(metadata_2$sample_name)], ]

# Reorder columns in metadata_2 to place SampleID as the first column
metadata_2 <- metadata_2[, c("SampleID", setdiff(names(metadata_2), "SampleID"))]
```


```{r}
# Identify rows in mapping_file where Filename_ID is not present in metadata_2$SampleID
missing_sample_ids <- mapping_file[!(mapping_file$Filename_ID %in% metadata_2$SampleID), ]

# Create a new data frame for missing SampleIDs
missing_sample_ids_df <- data.frame(SampleID = missing_sample_ids$Filename_ID)

# Add missing SampleIDs to metadata_final with other columns filled with NA
missing_rows <- data.frame(SampleID = missing_sample_ids_df$SampleID, 
                           matrix(NA, nrow = nrow(missing_sample_ids_df), ncol = ncol(metadata_2) - 1))
colnames(missing_rows) <- colnames(metadata_2)

# Remove any duplicate rows that might already exist in metadata_2
missing_rows <- missing_rows[!(missing_rows$SampleID %in% metadata_2$SampleID), ]

# Append missing rows to metadata_2 to create metadata_final
metadata_final <- rbind(metadata_2, missing_rows)

# Add a new column Sample_Type to metadata_final based on SampleID patterns
metadata_final <- metadata_final %>%
  mutate(Sample_Type = case_when(
    str_detect(SampleID, regex("wash", ignore_case = TRUE)) ~ "Wash",
    str_detect(SampleID, regex("Blank", ignore_case = TRUE)) ~ "Blank",
    str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE)) ~ "6mix",
    str_detect(SampleID, regex("Pool", ignore_case = TRUE)) ~ "Pooled samples",
    str_detect(SampleID, regex("CTL", ignore_case = TRUE)) ~ "CTL",
    TRUE ~ "samples"  # Default to 'samples' for SampleIDs that don't match the others
  ))

# Print or inspect the updated metadata_final with Sample_Type column
head(metadata_final)
```
```{r}
# Summarize counts of each Sample_Type in metadata_final
cat("Number of 'samples':", sum(metadata_final$Sample_Type == "samples"), "\n")
cat("Number of '6mix':", sum(metadata_final$Sample_Type == "6mix"), "\n")
cat("Number of 'Pooled samples':", sum(metadata_final$Sample_Type == "Pooled samples"), "\n")
cat("Number of 'CTL':", sum(metadata_final$Sample_Type == "CTL"), "\n")
cat("Number of 'Blank':", sum(metadata_final$Sample_Type == "Blank"), "\n")

# Summarize counts of each category_label in metadata
cat("Number of 'Healthy':", sum(metadata$category_label == "Healthy"), "\n")
cat("Number of 'Acne Lesional':", sum(metadata$category_label == "Acne Lesional"), "\n")
cat("Number of 'Acne Non-lesional':", sum(metadata$category_label == "Acne Non-lesional"), "\n")
```

```{r}
# L'Oreal Data Integration
# Merge metadata_final with sample_order by matching SampleID and File.Name
metadata_final <- metadata_final %>% left_join(sample_order, by = c("SampleID" = "File.Name"))

# Identify unmatched SampleIDs between metadata_final and sample_order
unmatched_metadata <- metadata_final %>%
  anti_join(sample_order, by = c("SampleID" = "File.Name"))

# View the unmatched metadata
unmatched_metadata

unmatched_sample_order <- sample_order %>%
  anti_join(metadata_final, by = c("File.Name" = "SampleID"))

# View the result
unmatched_sample_order
```

```{r}
# Check for duplicated SampleIDs after the join
duplicated_samples <- metadata_final %>%
  group_by(SampleID) %>%
  filter(n() > 1)

# Display the duplicated SampleIDs
cat("Duplicated SampleIDs after the join:\n")
print(duplicated_samples)

# Optionally, count the number of duplicates
num_duplicates <- nrow(duplicated_samples)
cat("\nNumber of duplicated SampleIDs after the join: ", num_duplicates, "\n")
```
```{r}
# Identify unmatched SampleIDs between sample_order and metadata_final
# Create a subset of rows from metadata_final that are not in sample_order
unmatched_metadata <- metadata_final %>%
  anti_join(sample_order, by = c("SampleID" = "File.Name"))

# View the unmatched metadata
unmatched_metadata

# Extract and prepare feature information from the feature_table
info_feature <- feature_table %>% dplyr::select(1:3,7)
colnames(info_feature) <- c("Feature", "mz", "RT", "Corr_ID")
info_feature$Feature <- as.character(info_feature$Feature)

# Merge feature information with annotations and CANOPUS data
info_feature_complete <- info_feature %>% 
  left_join(annotations, by = c("Feature" = "X.Scan.")) %>%
  dplyr::select(1:4,18,24) %>% 
  left_join(canopus %>% distinct(featureId, .keep_all = TRUE), by = c("Feature" = "featureId"))
```

```{r}
# Extract data table from feature_table
# Transform and clean up the data for analysis
data <- feature_table %>% 
  column_to_rownames("row ID") %>% dplyr::select(contains("Peak")) %>% 
  t() %>% as.data.frame() %>% rownames_to_column("SampleID") %>% 
  arrange(SampleID) %>% distinct(SampleID, .keep_all = TRUE)

# Clean up SampleID to remove unnecessary text
data$SampleID <- gsub(".mzML Peak area", "", data$SampleID)
```

```{r}
# Find the rows in mapping_file where Filename_ID is not present in metadata_final$SampleID
missing_sample_ids <- data[!(data$SampleID %in% metadata_final$SampleID), ]

# Find the rows in mapping_file where Filename_ID is not present in metadata_final$SampleID
missing_samples <- metadata_final[!(metadata_final$SampleID %in% data$SampleID), ]
# LAMI.RD318.D4.C1 did not run

metadata_ids <- metadata_final$SampleID
data_ids <- data$SampleID

# 1. Find SampleIDs in metadata_final but not in data
missing_in_data <- setdiff(metadata_ids, data_ids)

# 2. Find SampleIDs in data but not in metadata_final
missing_in_metadata <- setdiff(data_ids, metadata_ids)

# 3. Check for duplicated SampleIDs in metadata_final
duplicates_in_metadata <- metadata_ids[duplicated(metadata_ids)]

# 4. Check for duplicated SampleIDs in data
duplicates_in_data <- data_ids[duplicated(data_ids)]

# Print results
cat("SampleIDs in metadata_final but not in data:\n")
print(missing_in_data)

cat("\nSampleIDs in data but not in metadata_final:\n")
print(missing_in_metadata) # Should be none

cat("\nDuplicated SampleIDs in metadata_final:\n")
print(duplicates_in_metadata) # Should be none

cat("\nDuplicated SampleIDs in data:\n")
print(duplicates_in_data) # Should be none
```
```{r}
# Clean up SampleID to remove unnecessary text
data$SampleID <- gsub(".mzML Peak area", "", data$SampleID)

# Filter out specific samples from the dataset (blanks, QC mixes)
data_final <- data %>% 
  dplyr::filter(!(SampleID %in% c("blank_P2_0A_prerun", "blank_P3_0A_prerun_20241022011201", "blank_P3_0B_prerun", "blank_P1_0A_prerun", "QC_P1_6mix_0", "QC_P1_Pool_0", "QC_P1_6mix_0_20241019144629", "blank_P1_0A_prerun_20241019143524")))

# Check for missing samples in the dataset
samples_to_remove <- c("blank_P2_0A_prerun", "blank_P3_0A_prerun_20241022011201", "blank_P3_0B_prerun",
                       "blank_P1_0A_prerun", "QC_P1_6mix_0", "QC_P1_Pool_0","QC_P1_6mix_0_20241019144629", "blank_P1_0A_prerun_20241019143524")

# Identify samples that are in the list but not in the dataset
missing_samples <- setdiff(samples_to_remove, data$SampleID)

# Issue a warning if there are missing samples
if (length(missing_samples) > 0) {
  warning(paste("The following samples are not present in the dataset:", paste(missing_samples, collapse = ", ")))
}
```

```{r}
# QC PLOTS
# Calculate Total Ion Count (TIC)
data_TIC <- data.frame(TIC = rowSums(data_final %>% column_to_rownames("SampleID"))) %>% 
  rownames_to_column("SampleID") %>% left_join(sample_order, by = c("SampleID" = "File.Name"))

#Plots a scatter plot of the Order vs. TIC
data_TIC %>% dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  left_join(metadata_final) %>%
  ggscatter("Order", "TIC", color = "host_subject_id", add = "reg.line") +
  stat_cor()

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```
```{r}
# Check sample types based on Total Ion Count (TIC)
sample_tic <- data_TIC %>% 
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>% 
  summarise(mean(TIC))

pool_tic <- data_TIC %>% 
  dplyr::filter(str_detect(SampleID, regex("Pool", ignore_case = TRUE))) %>% 
  summarise(mean(TIC))

six_tic <- data_TIC %>% 
  dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE))) %>% 
  summarise(mean(TIC))

blank_tic <- data_TIC %>% 
  dplyr::filter(str_detect(SampleID, regex("blank", ignore_case = TRUE))) %>% 
  summarise(mean(TIC))

ctl_tic <- data_TIC %>% 
  dplyr::filter(str_detect(SampleID, regex("CTL", ignore_case = TRUE))) %>% 
  summarise(mean(TIC))

# Calculate TIC ratios
ratio_tic_pb <- pool_tic / sample_tic
ratio_tic_sb <- sample_tic / blank_tic
ratio_tic_6p <- pool_tic / six_tic

# Visualize TIC over time for different sample types
a0 <- data_TIC %>% dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() + ylim(0, 7e9) + ggtitle("TIC over Time for Samples")

a <- data_TIC %>% dplyr::filter((str_detect(SampleID, regex("Pool", ignore_case = TRUE)))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() + ylim(0, 7e9) + ggtitle("TIC over Time for Pooled Samples")

b <- data_TIC %>% dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() + ylim(0, 7e9) + ggtitle("TIC over Time for 6mix Samples")

c <- data_TIC %>% dplyr::filter((str_detect(SampleID, regex("blank", ignore_case = TRUE)))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() + ylim(0, 7e9) + ggtitle("TIC over Time for Blank Samples")

d <- data_TIC %>% dplyr::filter((str_detect(SampleID, regex("CTL", ignore_case = TRUE)))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() + ylim(0, 7e9) + ggtitle("TIC over Time for Blank Swab Samples (CTL)")

f <- ggarrange(a0, a, b, c, d, ncol = 3, nrow = 2, labels = c("a", "b", "c", "d", "e"))

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_all.png", plot = last_plot(), dpi = 600, width = 16, height = 10, units = "in")
```
```{r}
# Identify SampleIDs in data_TIC that are not in data_final
missing_sample_ids <- data_TIC$SampleID[!(data_final$SampleID %in% data_TIC$SampleID)]

# Display or print the missing SampleIDs
print(missing_sample_ids)

# Check for duplicate SampleIDs in data_TIC
duplicates_in_data_TIC <- data_TIC$SampleID[duplicated(data_TIC$SampleID)]

# Display the duplicate SampleIDs
print(duplicates_in_data_TIC)
```

```{r}
# Step 1: Filter by SampleID and count the remaining samples
filtered_by_sampleid <- data_TIC %>%
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE))))
count_after_sampleid <- nrow(filtered_by_sampleid)

# Step 2: Filter by TIC range within the previously filtered dataset and count
data_tic_filtered <- filtered_by_sampleid %>%
  dplyr::filter(TIC >= 6e8 & TIC <= 5e9)
count_after_tic <- nrow(data_tic_filtered)

# Step 3: Identify SampleIDs that do not meet both filtering criteria
# Samples in filtered_by_sampleid but not in data_tic_filtered
excluded_samples <- anti_join(filtered_by_sampleid, data_tic_filtered, by = "SampleID")

# Step 4: Remove these excluded samples from the original data_TIC
data_TIC_updated <- data_TIC %>%
  dplyr::anti_join(excluded_samples, by = "SampleID")

# Print counts for reference
cat("Initial sample count:", nrow(data_TIC), "\n")
cat("Count after SampleID filtering:", count_after_sampleid, "\n")
cat("Final count after TIC filtering:", count_after_tic, "\n")
cat("Remaining samples in data_TIC_final:", nrow(data_TIC_updated), "\n")

# Update data_final by excluding samples listed in excluded_samples
data_final_updated <- data_final %>% 
  dplyr::filter(!(SampleID %in% excluded_samples$SampleID))

# Display filtered data
head(data_TIC_updated)
```
```{r}
# Step 1: Filter out samples that match "Blank", "6mix", "Pool", "wash", "CTL", or "QC" from the subset
# and apply additional filtering to keep only those within the TIC range.
data_tic_filtered <- data_TIC %>%
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  dplyr::filter(TIC >= 6e8 & TIC <= 5e9)

# Step 2: Plot the filtered data to visualize TIC over time for the selected samples.
a0 <- data_tic_filtered %>%
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor()  +ylim(0, 7e9) +
  ggtitle("TIC over Time for Filtered Samples")

a <- data_TIC %>% dplyr::filter((str_detect(SampleID, regex("Pool", ignore_case = TRUE))))%>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() +ylim(0, 7e9) + ggtitle("TIC over Time for Pooled Samples")

b <- data_TIC %>%   dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE)))  %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() +ylim(0, 7e9) + ggtitle("TIC over Time for 6mix Samples")

c <- data_TIC %>% dplyr::filter((str_detect(SampleID, regex("blank", ignore_case = TRUE)))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor()  +ylim(0, 7e9) + ggtitle("TIC over Time for Blank Samples")

d <- data_TIC %>%  dplyr::filter((str_detect(SampleID, regex("CTL", ignore_case = TRUE)))) %>% 
  ggscatter("Order", "TIC", add = "reg.line") +
  stat_cor() +ylim(0, 7e9) + ggtitle("TIC over Time for Blank Swab Samples (CTL)")

f <- ggarrange(a0, a, b, c, d, ncol = 3, nrow = 2, labels = c("a", "b", "c", "d", "e"))

# Display the plot
print(a0)

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_all_filtered_5e8.png", plot = last_plot(), dpi = 600, width = 16, height = 10, units = "in")
```
```{r}
# Plot a scatter plot of the Order vs. TIC
data_tic_filtered %>% dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  left_join(metadata_final) %>%
  ggscatter("Order", "TIC", color = "host_subject_id", add = "reg.line") +
  stat_cor()

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_sampleID.png", plot = last_plot(), dpi = 600, width = 16, height = 10, units = "in")
```

```{r}
# Merge `sample_order` with `mapping_file` to include additional columns (`Filename_ID` and `Plate_Number`) 
# while retaining all rows from `sample_order`.
sample_order_2 <- merge(
  sample_order, 
  mapping_file[, c("Filename_ID", "Plate_Number")], 
  by.x = "File.Name", 
  by.y = "Filename_ID", 
  all.x = TRUE
)

# Merging the `data_TIC` DataFrame with `sample_order_2` based on matching `SampleID` in `data_TIC` with `File.Name` and `Order` with `Ord` in `sample_order_2`
data_tic_plate <- data_TIC %>%
  left_join(sample_order_2, by = c("SampleID" = "File.Name", "Order" = "Order"))

# SampleIDs in data_TIC that did not merge into data_tic_plate (i.e., not present in sample_order_2)
not_in_sample_order <- data_TIC %>%
  anti_join(sample_order_2, by = c("SampleID" = "File.Name", "Order" = "Order"))

# SampleIDs in sample_order_2 that did not merge into data_tic_plate (i.e., not present in data_TIC)
not_in_data_TIC <- sample_order_2 %>%
  anti_join(data_TIC, by = c("File.Name" = "SampleID", "Order" = "Order"))

# Convert Plate_Number to a factor for consistent coloring across all plots
data_tic_plate <- data_tic_plate %>%
  dplyr::mutate(Plate_Number = as.factor(Plate_Number))

# Define the mapping of specific colors to specific Plate_Number values
custom_colors <- c("1" = "#D55E00",  # Plate_Number == 1
                   "2" = "#2B579A",  # Plate_Number == 2
                   "3" = "#A1280B",  # Plate_Number == 3
                   "4" = "#217346")  # Plate_Number == 4

# TIC over Time for Samples (a0)
a0 <- data_tic_plate %>%
  dplyr::mutate(Plate_Number = as.factor(Plate_Number)) %>%
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>% 
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") +  # Map specific colors
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Samples")

# TIC over Time for Pooled Samples (a)
a <- data_tic_plate %>%
  dplyr::filter((str_detect(SampleID, regex("Pool", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Pooled Samples")

# TIC over Time for 6mix Samples (b)
b <- data_tic_plate %>%
  dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for 6mix Samples")

# TIC over Time for Blank Samples (c)
c <- data_tic_plate %>%
  dplyr::filter((str_detect(SampleID, regex("blank", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Blank Samples")

# TIC over Time for Blank Swab Samples (CTL) (d)
d <- data_tic_plate %>%
  dplyr::filter((str_detect(SampleID, regex("CTL", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Blank Swab Samples (CTL)")

f <- ggarrange(
  a0, a, b, c, d, 
  ncol = 3, nrow = 2, 
  labels = c("a", "b", "c", "d", "e"),
  common.legend = TRUE,  # Use a common legend
  legend = "bottom"      # Place the legend at the bottom
)

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_all_platenumber.png", plot = last_plot(), dpi = 600, width = 16, height = 10, units = "in")
```
```{r}
# Filter by TIC 
# Convert Plate_Number to a factor for consistent coloring across all plots
data_tic_plate <- data_tic_plate %>%
  dplyr::mutate(Plate_Number = as.factor(Plate_Number))

# Define the mapping of specific colors to specific Plate_Number values
custom_colors <- c("1" = "#D55E00",  # Plate_Number == 1
                   "2" = "#2B579A",  # Plate_Number == 2
                   "3" = "#A1280B",  # Plate_Number == 3
                   "4" = "#217346")  # Plate_Number == 4

# TIC over Time for Samples (a0)
a0 <- data_tic_plate %>%
  dplyr::mutate(Plate_Number = as.factor(Plate_Number)) %>%
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  dplyr::filter(TIC >= 6e8 & TIC <= 5e9) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") +  # Map specific colors
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Samples")

# TIC over Time for Pooled Samples (a)
a <- data_tic_plate %>%
  dplyr::filter((str_detect(SampleID, regex("Pool", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Pooled Samples")

# TIC over Time for 6mix Samples (b)
b <- data_tic_plate %>%
  dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for 6mix Samples")

# TIC over Time for Blank Samples (c)
c <- data_tic_plate %>%
  dplyr::filter((str_detect(SampleID, regex("blank", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Blank Samples")

# TIC over Time for Blank Swab Samples (CTL) (d)
d <- data_tic_plate %>%
  dplyr::filter((str_detect(SampleID, regex("CTL", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "Plate_Number") + 
  scale_color_manual(values = custom_colors, name = "Plate Number") + 
  stat_cor() +ylim(0, 7e9)+ 
  ggtitle("TIC over Time for Blank Swab Samples (CTL)")

```
```{r}
f <- ggarrange(
  a0, a, b, c, d, 
  ncol = 3, nrow = 2, 
  labels = c("a", "b", "c", "d", "e"),
  common.legend = TRUE,  # Use a common legend
  legend = "bottom"      # Place the legend at the bottom
)

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_all_platenumber_filtered.svg", plot = last_plot(), dpi = 600, width = 16, height = 10, units = "in")
```

```{r}
# Merging the `data_TIC` DataFrame with `metadata_2` to add metadata information based on matching `SampleID` in both DataFrames
data_tic_group <- data_TIC %>%
  left_join(metadata_2, by = c("SampleID" = "SampleID"))

# Define custom orange, pine green, brown, and Excel-style green color palette
custom_colors <- c("#df7963", "#67b2be", "#423fa6")  


# TIC over Time for Samples (a0)
a0 <- data_tic_group %>%
  dplyr::mutate(group = as.factor(category_label)) %>%
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "group") + 
  scale_color_manual(values = custom_colors, name = "group") +  # Use custom color palette
  stat_cor() + 
  ggtitle("TIC over Time for Samples")

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_group.png", plot = last_plot(), dpi = 600, width = 8, height = 8, units = "in")
```

```{r}
# Merging the `data_TIC` DataFrame with `metadata_2` to add metadata information based on matching `SampleID` in both DataFrames
data_tic_group <- data_TIC %>%
  left_join(metadata_2, by = c("SampleID" = "SampleID"))

# Define custom orange, pine green, brown, and Excel-style green color palette
custom_colors <- c("#df7963", "#67b2be", "#423fa6")  

# TIC over Time for Samples (a0)
a0 <- data_tic_group %>%
  dplyr::mutate(group = as.factor(category_label)) %>%
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  ggscatter(x = "Order", y = "TIC", color = "group") + 
  scale_color_manual(values = custom_colors, name = "group") +  # Use custom color palette
  stat_cor() + 
  ggtitle("TIC over Time for Samples")

ggsave("../Figures/metabolomics_Figures/qc/TICvsOrder_group_filtered.png", plot = last_plot(), dpi = 600, width = 8, height = 8, units = "in")
```

```{r}
# Find the 6mix antibiotics
abundance_data <- subset(data_final_updated, SampleID == "QC_P2_6mix_4")

# Remove the SampleID column before transposing
abundance_data <- abundance_data[ , !(names(abundance_data) %in% "SampleID")]

# Transpose the data and convert values to numeric
abundance_data <- as.data.frame(t(abundance_data))
abundance_data <- as.numeric(as.matrix(abundance_data))

# Check internal standard and remove sample where there was a shift
fbmn_IS <- annotations %>% dplyr::filter(str_detect(Compound_Name, regex("sulf", ignore_case = TRUE))) %>% 
  distinct(X.Scan., .keep_all = TRUE) %>% dplyr::filter(Organism != "BILELIB19")

# Check internal standard and remove sample where there was a shift
fbmn_IS <- annotations %>% dplyr::filter(str_detect(Compound_Name, regex("Amitri", ignore_case = TRUE))) %>% 
  distinct(X.Scan., .keep_all = TRUE) %>% dplyr::filter(Organism != "BILELIB19")

# Extract IS feature from the table
table_IS <- data_final %>% column_to_rownames("SampleID") %>% t() %>% as.data.frame() %>% rownames_to_column("ID") %>%
  dplyr::filter(ID %in% fbmn_IS$X.Scan.) %>% column_to_rownames("ID") %>% t() %>% as.data.frame() %>%
  rownames_to_column("filename") %>% left_join(metadata_final, by = c("filename" = "SampleID")) %>%
  dplyr::filter(!(str_detect(filename, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE))))# %>%
  #dplyr::select(filename, `15435`, Order, filename)
  # dplyr::select(filename, `15435`, Order, filename)

# Renaming the second column of `table_IS` to "sulfadimethoxine"
colnames(table_IS)[2] <- "sulfadimethoxine"

# Creating a scatter plot of "Order" vs. "sulfadimethoxine" with a regression line, correlation statistics, and setting y-axis limits
table_IS %>% 
  ggscatter(x = "Order", y = "sulfadimethoxine", add = c("reg.line")) +
  stat_cor() + # Adds correlation coefficient and p-value to the plot
  ylim(0, 5e6) # Sets y-axis limits from 0 to 5,000,000

ggsave("../Figures/metabolomics_Figures/qc/scatter_IS_filtered.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```
#Scan Numbers of the 6 antibiotics (Sulfadimethoxine was the one that was used according to Jasmine )
10110 Sulfamethazine
15435 Sulfadimethoxine
16885 Amitriptyline
21848 Coumarin
12511 Sulfachloropyridazine
10762 Sulfadimethizole

```{r}
# Make plot for all 6-mix antibiotics

colnames(table_IS)[2] <- "Coumarin_314"

Coumarin <- table_IS %>% ggscatter(x = "Order", y = "Coumarin_314", add = c("reg.line")) +
  stat_cor() + ylim(0, 7e9)#+ ylim(0, 4e7)

cv_is <- sd(table_IS$Coumarin_314)/mean(table_IS$Coumarin_314)
#24.75%

colnames(table_IS)[2] <- "Sulfachloropyridazine"

Sulfachloropyridazine <- table_IS %>% ggscatter(x = "Order", y = "Sulfachloropyridazine", add = c("reg.line")) +
  stat_cor() + ylim(0, 7e9)#+ ylim(0, 4e7)

cv_is <- sd(table_IS$Sulfachloropyridazine)/mean(table_IS$Sulfachloropyridazine)
#66.78%

colnames(table_IS)[2] <- "Sulfadimethizole"

Sulfadimethizole <- table_IS %>% ggscatter(x = "Order", y = "Sulfadimethizole", add = c("reg.line")) +
  stat_cor() + ylim(0, 7e9)#+ ylim(0, 4e7)

cv_is <- sd(table_IS$Sulfadimethizole)/mean(table_IS$Sulfadimethizole)
#68.34%

colnames(table_IS)[2] <- "Amitriptyline"

Amitriptyline <- table_IS %>% ggscatter(x = "Order", y = "Amitriptyline", add = c("reg.line")) +
  stat_cor()  + ylim(0, 7e9)#+ ylim(0, 4e7)

cv_is <- sd(table_IS$Amitriptyline)/mean(table_IS$Amitriptyline)
#29.3%

colnames(table_IS)[2] <- "Sulfadimethoxine"

sulfadimethoxine <- table_IS %>% ggscatter(x = "Order", y = "Sulfadimethoxine", add = c("reg.line")) +
  stat_cor() + ylim(0, 7e9)#+ ylim(0, 4e7)

cv_is <- sd(table_IS$Sulfadimethoxine)/mean(table_IS$Sulfadimethoxine)
#60.5%

#10110
colnames(table_IS)[2] <- "Sulfamethazine"

sulfamethazine <- table_IS %>% ggscatter(x = "Order", y = "Sulfamethazine", add = c("reg.line")) +
  stat_cor() + ylim(0, 7e9)#ylim(0, 4e7)
cv_is <- sd(table_IS$Sulfamethazine)/mean(table_IS$Sulfamethazine)
#72.5%

f <- ggarrange(
  sulfamethazine, sulfadimethoxine, Amitriptyline, Sulfadimethizole, Sulfachloropyridazine, Coumarin,
  ncol = 3, nrow = 2, 
  labels = c("a", "b", "c", "d", "e", "f"),
  common.legend = TRUE,  # Use a common legend
  legend = "bottom"      # Place the legend at the bottom
)

ggsave("../Figures/metabolomics_Figures/qc/sixmix_antibiotics_7e9.png", plot = last_plot(), dpi = 600, width = 12, height = 8, units = "in")

ggsave("../Figures/metabolomics_Figures/qc/PeakArea_IS_sulfamethazine.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")

ggsave("../Figures/metabolomics_Figures/qc/PeakArea_IS_filtered.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```

```{r}
# Filter table_IS for filenames with sulfadimethoxin < 22378
filtered_table_IS <- table_IS[table_IS$sulfadimethoxin < 1e6, "filename"]

# Filter data_TIC for SampleIDs with TIC < 569590420
filtered_data_TIC <- data_TIC[data_TIC$TIC < 5e8, "SampleID"]

# Find common values
common_filenames <- intersect(filtered_table_IS, filtered_data_TIC)

# Find values in table_IS but not in data_TIC
unique_to_table_IS <- setdiff(filtered_table_IS, filtered_data_TIC)

# Find values in data_TIC but not in table_IS
unique_to_data_TIC <- setdiff(filtered_data_TIC, filtered_table_IS)

# Print results
cat("Common filenames:\n")
print(common_filenames)

cat("\nFilenames in table_IS but not in data_TIC:\n")
print(unique_to_table_IS)

cat("\nFilenames in data_TIC but not in table_IS:\n")
print(unique_to_data_TIC)
```
```{r}
# Check features in blanks and pools
data_blank <- data_final %>% dplyr::filter((str_detect(SampleID, regex("blank", ignore_case = TRUE)))) 
data_pools <- data_final %>% dplyr::filter((str_detect(SampleID, regex("Pool", ignore_case = TRUE))))
data_sixmix <- data_final %>% dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE)))
data_CTL <- data_final %>% dplyr::filter((str_detect(SampleID, regex("CTL", ignore_case = TRUE))))

# Check features in blanks and pools with filtering out the outliers
data_blank <- data_final_updated %>% dplyr::filter((str_detect(SampleID, regex("blank", ignore_case = TRUE)))) 
data_pools <- data_final_updated %>% dplyr::filter((str_detect(SampleID, regex("Pool", ignore_case = TRUE))))
data_sixmix <- data_final_updated %>% dplyr::filter(str_detect(SampleID, "^QC_P[0-9]+_[0-9]+$") | str_detect(SampleID, regex("6mix", ignore_case = TRUE)))
data_CTL <- data_final_updated %>% dplyr::filter((str_detect(SampleID, regex("CTL", ignore_case = TRUE))))

# Get feature info for blanks
blanks_feature_info <- data.frame(Feature = colnames(data_blank)[-1],
                                  Mean_blank = data_blank %>% column_to_rownames("SampleID") %>% colMeans(), 
                                  SD_blank =  data_blank %>% column_to_rownames("SampleID") %>% apply(2, sd)) %>%
  dplyr::mutate(CV_blank = SD_blank/Mean_blank) %>% left_join(annotations, by = c("Feature" = "X.Scan.")) %>% 
  left_join(info_feature) %>% dplyr::select(Feature, mz, RT, Compound_Name, SpectrumID, 
                                            Precursor_MZ, Mean_blank, SD_blank, CV_blank) %>% 
  dplyr::filter(Mean_blank > 0) %>% arrange(desc(Mean_blank))

# Get feature info for six mix
sixmix_feature_info <- data.frame(Feature = colnames(data_sixmix)[-1],
                                  Mean_sixmix = data_sixmix %>% column_to_rownames("SampleID") %>% colMeans(), 
                                  SD_sixmix = data_sixmix %>% column_to_rownames("SampleID") %>% apply(2, sd)) %>%
  dplyr::mutate(CV_sixmix = SD_sixmix/Mean_sixmix) %>% left_join(annotations, by = c("Feature" = "X.Scan.")) %>% 
  left_join(info_feature) %>% dplyr::select(Feature, mz, RT, Compound_Name, SpectrumID, 
                                            Precursor_MZ, Mean_sixmix, SD_sixmix, CV_sixmix) %>% 
  dplyr::filter(Mean_sixmix > 0) %>% arrange(desc(Mean_sixmix))

# Get feature info for pool
pools_feature_info <- data.frame(Feature = colnames(data_pools)[-1],
                                 Mean_pool = data_pools %>% column_to_rownames("SampleID") %>% colMeans(), 
                                 SD_pool =  data_pools %>% column_to_rownames("SampleID") %>% apply(2, sd)) %>%
  dplyr::mutate(CV_pool = SD_pool/Mean_pool) %>% left_join(annotations, by = c("Feature" = "X.Scan.")) %>% 
  left_join(info_feature) %>% dplyr::select(Feature, mz, RT, Compound_Name, SpectrumID, 
                                            Precursor_MZ, Mean_pool, SD_pool, CV_pool) %>% 
  dplyr::filter(Mean_pool > 0) %>% arrange(desc(Mean_pool))

# Get feature info for CTLs
CTLs_feature_info <- data.frame(Feature = colnames(data_CTL)[-1],
                                 Mean_ctl = data_CTL %>% column_to_rownames("SampleID") %>% colMeans(), 
                                 SD_ctl =  data_CTL %>% column_to_rownames("SampleID") %>% apply(2, sd)) %>%
  dplyr::mutate(CV_ctl = SD_ctl/Mean_ctl) %>% left_join(annotations, by = c("Feature" = "X.Scan.")) %>% 
  left_join(info_feature) %>% dplyr::select(Feature, mz, RT, Compound_Name, SpectrumID, 
                                            Precursor_MZ, Mean_ctl, SD_ctl, CV_ctl) %>% 
  dplyr::filter(Mean_ctl > 0) %>% arrange(desc(Mean_ctl))
```


```{r}
# Features to be removed Pools/Blank < 5 or 10
feature_to_remove <- blanks_feature_info %>% left_join(pools_feature_info) %>%
  dplyr::filter(Mean_blank > 0) %>% 
  dplyr::mutate(Pool_Blank = Mean_pool/Mean_blank) %>% 
  dplyr::filter(Pool_Blank < 5 | is.na(Pool_Blank))

# Data with blank removal
data_clean <- data_final %>% dplyr::select(-c(feature_to_remove$Feature)) %>%
  column_to_rownames("SampleID") %>%
  select_if(~sum(.) != 0) %>% rownames_to_column("SampleID")

# Data with blank removal after outlier removal
data_clean <- data_final_updated %>% dplyr::select(-c(feature_to_remove$Feature)) %>%
  column_to_rownames("SampleID") %>%
  select_if(~sum(.) != 0) %>% rownames_to_column("SampleID")

# Features to be removed Pool/QCmix < 5 or 10 
feature_to_remove_mix <- sixmix_feature_info %>% left_join(pools_feature_info) %>% 
  dplyr::filter(Mean_sixmix > 0) %>% 
  dplyr::mutate(Pool_Mix = Mean_pool/Mean_sixmix) %>% 
  dplyr::filter(Pool_Mix < 5 | is.na(Pool_Mix)) %>% dplyr::filter(!(Feature %in% feature_to_remove$Feature))

# Data with blank2 removal
data_clean2 <- data_clean %>% dplyr::select(-c(feature_to_remove_mix$Feature))

# Features to be removed Pool/CTL < 5 or 10 
feature_to_remove_ctl <- CTLs_feature_info %>% left_join(pools_feature_info) %>% 
  dplyr::filter(Mean_ctl > 0) %>% 
  dplyr::mutate(Pool_CTL = Mean_pool/Mean_ctl) %>% 
  dplyr::filter(Pool_CTL < 5 | is.na(Pool_CTL)) %>% dplyr::filter(!(Feature %in% feature_to_remove_mix$Feature))  %>%  dplyr::filter(!(Feature %in% feature_to_remove$Feature))

# Data with blank2 removal
data_clean3 <- data_clean2 %>% dplyr::select(-c(feature_to_remove_ctl$Feature))
```

```{r}
# Define the color palette for six Sample_Type categories
sample_type_colors <- c("samples" = "#1f77b4",  # Blue
                        "Blank" = "#ff7f0e",  # Orange
                        "Pooled samples" = "#2ca02c",  # Green
                        "CTL" = "#d62728",  # Red
                        "6mix" = "#9467bd",  # Purple
                        "Wash" = "#8c564b")  # Brown

# PCA raw data
PCA_raw <- mixOmics::pca(data_clean2 %>% select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>%
                           column_to_rownames("SampleID"), ncomp = 2, center = TRUE, scale = TRUE)
PCA_raw_scores <- data.frame(PCA_raw$variates$X) %>% rownames_to_column("SampleID") %>% left_join(metadata_final)

i <- "Sample_Type"

PCA_raw_plot <- PCA_raw_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - Skin Metabolome", i, sep = " "),
            xlab = paste("PC1 (", round(PCA_raw$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_raw$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_raw_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed() +
  scale_color_manual(values = sample_type_colors)

ggsave("../Figures/metabolomics_Figures/qc/PCA_data_clean2.png", plot = last_plot(), dpi = 600, width = 10, height = 6, units = "in")
```
```{r}
# PCA raw data
PCA_raw <- mixOmics::pca(data_clean3 %>% select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>%
                           column_to_rownames("SampleID"), ncomp = 2, center = TRUE, scale = TRUE)
PCA_raw_scores <- data.frame(PCA_raw$variates$X) %>% rownames_to_column("SampleID") %>% left_join(metadata_final)

i <- "Sample_Type"

PCA_raw_plot <- PCA_raw_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - Skin Metabolome", i, sep = " "),
            xlab = paste("PC1 (", round(PCA_raw$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_raw$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_raw_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed() +
  scale_color_manual(values = sample_type_colors)

ggsave("../Figures/metabolomics_Figures/qc/PCA_data_clean3.png", plot = last_plot(), dpi = 600, width = 10, height = 6, units = "in")

ggsave("../Figures/metabolomics_Figures/qc/PCA_qc_5_filtered.png", plot = last_plot(), dpi = 600, width = 10, height = 6, units = "in")

ggsave("../Figures/metabolomics_Figures/qc/PCA_qc_5.svg", plot = last_plot(), dpi = 600, width = 10, height = 6, units = "in")
```
```{r}
# Applying a robust center log-ratio (rCLR) transformation to `data_clean2` after setting `SampleID` as row names
data_clean_2_clr <- decostand(data_clean2 %>% column_to_rownames("SampleID"), method = "rclr")

# Plot PCA
PCA_whole <- mixOmics::pca(data_clean_2_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_whole_scores <- data.frame(PCA_whole$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)
PCA_whole_scores <- data.frame(PCA_whole$variates$X) %>% rownames_to_column("SampleID") %>% left_join(metadata_final)
i <- "Sample_Type"

PCA_plot <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - Skin Metabolome - rclr transformed data"),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed()  +
  scale_color_manual(values = sample_type_colors)

ggsave("../Figures/metabolomics_Figures/qc/PCA_rclr_dataclean3.png", plot = last_plot(), dpi = 600, width = 10, height = 6, units = "in")
```
```{r}
# Arranging the PCA_raw_plot and PCA_plot side by side with a shared legend
f <- ggarrange(
  PCA_raw_plot, PCA_plot,  # Plots to arrange
  ncol = 2, nrow = 1,  # Number of columns and rows for the arrangement
  labels = c("a", "b"),  # Labels for the plots
  common.legend = TRUE,  # Use a common legend for both plots
  legend = "right",  # Place the legend to the right of the plots
  align = "hv"  # Align the plots both horizontally and vertically
)

ggsave("../Figures/metabolomics_Figures/qc/PCA_combined_filtered.svg", plot = last_plot(), dpi = 600, width = 10, height = 6, units = "in")
```

```{r}
# Remove plastic contamination
feature_check <- info_feature %>% dplyr::select(1:3) %>% 
  dplyr::filter(Feature %in% colnames(data_clean)) %>% as_tibble()
colnames(feature_check) <- c("peak_id", "mz", "rt")
feature_check$mz <- as.double(feature_check$mz)
feature_check$rt <- as.double(feature_check$rt)

# for 1 CTL sample 
feature_pool <- data_clean2 %>% 
  dplyr::filter(SampleID == "P4_A1_LAMI_CTL_19") %>% column_to_rownames("SampleID") %>%
  t() %>% as.data.frame() %>% rownames_to_column("peak_id")

feature_check_pool <- feature_check %>% left_join(feature_pool)

feature_check_pool$peak_id <- as.integer(feature_check_pool$peak_id)
colnames(feature_check_pool)[4] <- "intensity"

# Remove plastic contamination after removing CTLs (data_clean3)
feature_check <- info_feature %>% dplyr::select(1:3) %>% 
  dplyr::filter(Feature %in% colnames(data_clean3)) %>% as_tibble()
colnames(feature_check) <- c("peak_id", "mz", "rt")
feature_check$mz <- as.double(feature_check$mz)
feature_check$rt <- as.double(feature_check$rt)

# for 1 CTL sample 
feature_pool <- data_clean3 %>% 
  dplyr::filter(SampleID == "P4_A1_LAMI_CTL_19") %>% column_to_rownames("SampleID") %>%
  t() %>% as.data.frame() %>% rownames_to_column("peak_id")

feature_check_pool <- feature_check %>% left_join(feature_pool)

feature_check_pool$peak_id <- as.integer(feature_check_pool$peak_id)
colnames(feature_check_pool)[4] <- "intensity"

# Remove PEGs
peak_table_PEG <- detectHomologues(feature_check_pool, mz_steps = c(44.02628),
                                   rt_min = 0.1, rt_max = 100, ppm_tolerance = 10, 
                                   min_series_length = 5, search_mode = "targeted", 
                                   step_mode = "increment", verbose = TRUE)

plotAnnotatedStatic(peak_table_PEG)
```
```{r}
# Creating a Spectral DataBase (sdb) object using `peak_table_PEG` with the sample origin specified as "data"
sdb <- sdbCreate(peak_table_PEG, sample_origin = "data")
```

```{r}
# Remove untargeted 
peak_table_untargeted <- detectHomologues(feature_check_pool, mz_min = 10, mz_max = 50, 
                                          rt_min = 0.5, rt_max = 100, ppm_tolerance = 5, 
                                          min_series_length = 5, search_mode = "untargeted", 
                                          step_mode = "increment", verbose = TRUE) #rt_min 0.5 -> 0.2 mz_max 50 -> 100 # increment -> decrement (and combine )
```
```{r}
# FOR THE ANNOTATION OF PEGs

# Detect homologues in the untargeted mode with specific parameters
peak_table_untargeted <- detectHomologues(
  feature_check_pool, 
  mz_min = 10, mz_max = 100,  # Mass-to-charge ratio range
  rt_min = 0.2, rt_max = 200,  # Retention time range
  ppm_tolerance = 5,  # Parts-per-million tolerance for matching
  min_series_length = 5,  # Minimum length of homologue series
  search_mode = "untargeted",  # Perform untargeted search
  step_mode = "decrement",  # Use decrement step mode (instead of increment)
  verbose = TRUE  # Print progress and information
)

# Generate a static plot of the annotated features
a <- plotAnnotatedStatic(peak_table_untargeted)

# If running both targeted and untargeted analysis, combine the results

# Check for overlapping homologue IDs between the spectral database and the untargeted peak table
overlapping_ids <- sdbCheckContained(sdb, peak_table_untargeted, ppm_tolerance = 0.5, rt_tolerance = 0.5)

# Push non-overlapping homologue IDs from the untargeted peak table into the spectral database
sdb <- sdbPush(sdb, filter(peak_table_untargeted, !(homologue_id %in% overlapping_ids)))

# Ensure the `sample_peak_id` in the spectral database is a character type
sdb$sample_peak_id <- as.character(sdb$sample_peak_id)

# Identify features classified as contaminants based on the complete feature information
features_contaminat <- info_feature_complete %>%
  dplyr::filter(Feature %in% sdb$sample_peak_id)

# Clean the data by removing contaminant features
data_clean4 <- data_clean3 %>% dplyr::select(-c(sdb$sample_peak_id))

# Example: Check one of the PEGs (use specific homologue IDs like 30108 or 26921)

# Select a PEG (e.g., ID 27183) and join it with metadata for further analysis
peg <- data_final %>%
  dplyr::select(SampleID, `27183`) %>%  # Extract PEG ID 27183 and SampleID
  left_join(metadata_final)  # Join with metadata

# Rename the second column to "PEG"
colnames(peg)[2] <- "PEG"

# Plot the PEG values using a boxplot grouped by Sample_Type
peg %>%
  arrange(Order) %>%  # Arrange samples by order
  dplyr::mutate(LogPeg = log2(PEG + 1)) %>%  # Transform PEG values using log2
  ggboxplot(
    x = "Sample_Type", y = "PEG", add = "jitter",  # Plot PEG values by Sample_Type
    color = "Order", group = "Sample_Type", legend = "right"  # Color by order and group by Sample_Type
  ) + 
  scale_color_viridis_c()  # Use a viridis color scale

# Repeat the analysis on the updated data
peg <- data_final_updated %>%
  dplyr::select(SampleID, `27183`) %>%  # Extract PEG ID 27183 and SampleID
  left_join(metadata_final)  # Join with metadata

# Rename the second column to "PEG"
colnames(peg)[2] <- "PEG"

# Plot the PEG values using a boxplot grouped by Sample_Type
peg %>%
  arrange(Order) %>%  # Arrange samples by order
  dplyr::mutate(LogPeg = log2(PEG + 1)) %>%  # Transform PEG values using log2
  ggboxplot(
    x = "Sample_Type", y = "PEG", add = "jitter",  # Plot PEG values by Sample_Type
    color = "Order", group = "Sample_Type", legend = "right"  # Color by order and group by Sample_Type
  ) + 
  scale_color_viridis_c()  # Use a viridis color scale
```

```{r}
# a is defined further 
# remove features with ID_cor=315

# Filter the column names to remove based on the condition
columns_to_remove <- a$names[a$Corr_ID == 315]

# Remove those columns from data_clean4 and save as data_clean5
data_clean5 <- data_clean4 %>% dplyr::select(-all_of(columns_to_remove))

# a and b are defined further
# Filter the column names to remove based on the condition and remove any NA values
#columns_to_remove <- a$names[a$Corr_ID == 315]
#columns_to_remove <- columns_to_remove[!is.na(columns_to_remove)]


columns_to_remove <- info_feature_complete$Feature[info_feature_complete$Corr_ID == 315]
columns_to_remove <- columns_to_remove[!is.na(columns_to_remove)]

# Keep only the columns that exist in data_clean4
columns_to_remove <- columns_to_remove[columns_to_remove %in% colnames(data_clean4)]

# Remove those columns from data_clean4 and save as data_clean5
data_clean5 <- data_clean4 %>% dplyr::select(-all_of(columns_to_remove))


#a and b are defined further
columns_to_remove <- info_feature_complete$Feature[info_feature_complete$Corr_ID == 403]
columns_to_remove <- columns_to_remove[!is.na(columns_to_remove)]

# Keep only the columns that exist in data_clean4
columns_to_remove <- columns_to_remove[columns_to_remove %in% colnames(data_clean5)]

# Remove those columns from data_clean4 and save as data_clean5
data_clean6 <- data_clean5 %>% dplyr::select(-all_of(columns_to_remove))
```

```{r}
# PCA
PCA_raw <- mixOmics::pca(data_clean4 %>% select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>%
                           column_to_rownames("SampleID"), ncomp = 2, center = TRUE, scale = TRUE)
PCA_raw_scores <- data.frame(PCA_raw$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

i <- "Sample_Type"

PCA_raw_plot <- PCA_raw_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - Skin Metabolome", i, sep = " "),
            xlab = paste("PC1 (", round(PCA_raw$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_raw$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_raw_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed()

ggsave("../Figures/metabolomics_Figures/qc/PCA_raw_HD.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")

ggsave("../Figures/metabolomics_Figures/qc/PCA_raw_HD_filtered.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")

```

```{r}
# Calculate Total Ion Count (TIC)
data_TIC_clean4 <- data.frame(TIC = rowSums(data_clean4 %>% column_to_rownames("SampleID"))) %>% 
  rownames_to_column("SampleID") %>% left_join(sample_order, by = c("SampleID" = "File.Name"))

#Plots a scatter plot of the Order vs. TIC
data_TIC_clean4 %>% dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  left_join(metadata_final) %>%
  ggscatter("Order", "TIC", color = "host_subject_id", add = "reg.line") +
  stat_cor()

# Calculate Total Ion Count (TIC)
data_TIC_clean6 <- data.frame(TIC = rowSums(data_clean6 %>% column_to_rownames("SampleID"))) %>% 
  rownames_to_column("SampleID") %>% left_join(sample_order, by = c("SampleID" = "File.Name"))

#Plots a scatter plot of the Order vs. TIC
data_TIC_clean6 %>% dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  left_join(metadata_final) %>%
  ggscatter("Order", "TIC", color = "host_subject_id", add = "reg.line") +
  stat_cor()

ggsave("../Figures/metabolomics_Figures/qc/data_TIC_clean6.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```
```{r}
# Keep only samples
#data_clean4 or data_clean5 or data_clean6
data_sample <- data_clean6 %>% 
   dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% rownames_to_column("SampleID")

# data_sample <- data_clean4 %>% 
#    dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>% 
#   column_to_rownames("SampleID") %>% 
#   select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% rownames_to_column("SampleID")

data_sample_method1 <- data_clean6 %>% 
   dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% rownames_to_column("SampleID")

write_csv(x = data_sample, file = "../Data/metabolomics/Run3_10252024/data_sample_10282024.csv")

write_csv(x = info_feature_complete, file = "../Data/metabolomics/Run3_10252024/info_feature_complete.csv")
```

```{r}
# Assuming metadata_final contains SampleID and sample_name columns

# Replace SampleID with sample_name
data_sample_name <- data_clean3 %>% 
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  dplyr::left_join(metadata_final %>% select(SampleID, sample_name), by = "SampleID") %>%
  dplyr::mutate(SampleID = sample_name) %>%
  dplyr::select(-sample_name) %>%
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")

```

```{r}

write_csv(x = data_sample_name, file = "../Data/metabolomics/Run3_10252024/data_sample_10282024.csv")
```

```{r}
# Replace SampleID with sample_name 09 29 2023
data_sample_name <- data_sample %>% 
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  dplyr::left_join(metadata_final %>% select(SampleID, sample_name), by = "SampleID") %>%
  dplyr::mutate(SampleID = sample_name) %>%
  dplyr::select(-sample_name) %>%
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")
```

```{r}
write_csv(x = data_sample_name, file = "../Data/metabolomics/Run3_10252024/output/quantwithoutblancs_09262024.csv")
```
```{r}
write_csv(x = data_sample_name, file = "../Data/metabolomics/Run3_10252024/output/data_sample_09292024.csv")
```

```{r}
# Assuming 'data_sample' contains a column 'SampleID' and 'metadata_final' has 'SampleID' and 'Plate_Number'
# Step 1: Get the SampleIDs that have Plate_Number equal to 2
exclude_samples <- metadata_final %>%
  filter(Plate_Number == 2) %>%
  pull(SampleID)

# Step 2: Remove those SampleIDs from data_sample
data_sample_filtered <- data_sample %>%
  filter(!SampleID %in% exclude_samples)

# Now, 'data_sample_filtered' contains only the rows where SampleID is not from Plate 2
```
```{r}
# Filter out rows where Plate_Number is equal to 2
metadata_filtered <- metadata_final %>%
  filter(Plate_Number != 2)
```
```{r}
# Replace SampleID with sample_name
data_sample_name <- data_sample_filtered %>% 
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  dplyr::left_join(metadata_filtered %>% select(SampleID, sample_name), by = "SampleID") %>%
  dplyr::mutate(SampleID = sample_name) %>%
  dplyr::select(-sample_name) %>%
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")
```


```{r}
write_csv(x = metadata_filtered, file = "../Data/metabolomics/Run3_10252024/output/metadata_filtered_09292024.csv")
```
```{r}
write_csv(x = metadata_final, file = "../Data/metabolomics/Run3_10252024/output/metadata_09262024.csv")
```

```{r}
write_csv(x = data_sample_name, file = "../Data/metabolomics/Run3_10252024/output/data_sample_filtered_09292024.csv")
```

```{r}
data_sample <- data_sample_filtered
```

```{r}
# RCLR transformation
data_sample_clr <- decostand(data_sample %>% column_to_rownames("SampleID"), method = "rclr")
```


```{r}
# PCA
PCA_whole <- mixOmics::pca(data_sample_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_whole_scores <- data.frame(PCA_whole$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)
PCA_whole_scores$category_label <- factor(PCA_whole_scores$category_label, levels = c("Healthy", "Acne Lesional", "Acne Non-lesional"))

i <- "category_label"

PCA_plot <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - group"),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed() + scale_color_viridis_d()

```
```{r}
ggsave("../Figures/metabolomics_Figures/qc/PCA_category_label_data_removaloutliersPC1.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```

```{r}
# Identify SampleIDs with PC1 > 10
outlier_sample_ids <- PCA_whole_scores %>%
  filter(PC1 > 10) %>%
  pull(SampleID)

# Display the outlier SampleIDs
print(outlier_sample_ids)

# Exclude these samples from data_sample_clr
data_sample_clr_filtered <- data_sample_clr[!rownames(data_sample_clr) %in% outlier_sample_ids, ]
```

```{r}
# Check if all outlier IDs are present in both datasets
all(outlier_sample_ids %in% rownames(data_sample))
all(outlier_sample_ids %in% rownames(data_sample_clr))

```

```{r}
# Filter data_sample based on SampleID column
data_sample_filtered <- data_sample %>%
  filter(!SampleID %in% outlier_sample_ids)

```

```{r}
# Filter data_sample based on SampleID column
data_sample_method2 <- data_sample %>%
  filter(!SampleID %in% outlier_sample_ids)
```



```{r}
# not a step for the filtering of the data
#create csv with all features and no filtering! 
# Filter data_sample based on SampleID column
data_sample_filtered <- data_final_updated %>%
  filter(!SampleID %in% outlier_sample_ids)

# Replace SampleID with sample_name
data_sample_name <- data_sample_filtered %>% 
  dplyr::filter(!(str_detect(SampleID, regex("Blank|6mix|Pool|wash|CTL|QC", ignore_case = TRUE)))) %>%
  dplyr::left_join(metadata_final %>% select(SampleID, sample_name), by = "SampleID") %>%
  dplyr::mutate(SampleID = sample_name) %>%
  dplyr::select(-sample_name) %>%
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")

write_csv(x = data_sample_name, file = "../Data/metabolomics/Run3_10252024/raw_data_11252024.csv")
```


```{r}
# RCLR transformation of all samples
data_sample_clr <- decostand(data_sample_filtered %>% column_to_rownames("SampleID"), method = "rclr")
```

```{r}
# Identify columns with zero variance
zero_variance_cols <- which(apply(data_sample_clr, 2, var) == 0)

# Remove columns with zero variance
data_sample_clr <- data_sample_clr[, -zero_variance_cols]

```

```{r}
# PCA
PCA_whole <- mixOmics::pca(data_sample_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_whole_scores <- data.frame(PCA_whole$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)
PCA_whole_scores$Plate_Number <- factor(PCA_whole_scores$Plate_Number, levels = c("1","2", "3", "4"))

i <- "Plate_Number"

PCA_plot <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - Plate_Number"),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed() + scale_color_viridis_d()

ggsave("../Figures/metabolomics_Figures/qc/PCA_Plate_Number.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```
```{r}
# PCA
PCA_whole <- mixOmics::pca(data_sample_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_whole_scores <- data.frame(PCA_whole$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

i <- "host_subject_id"

PCA_plot <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - host subject ID"),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed() #+ scale_color_viridis_d()
```

```{r}
# Generate a color palette with more than 20 colors (for example, 30 colors)
num_colors <- length(unique(PCA_whole_scores[[i]])) # Dynamic based on unique host subject IDs
palette <- colorRampPalette(brewer.pal(12, "Paired"))(num_colors)

PCA_plot <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
            title = paste("PCA - host subject ID"),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + 
  coord_fixed() +
  scale_color_manual(values = palette)

ggsave("../Figures/metabolomics_Figures/qc/PCA_host_subject_ID.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```
```{r}
a <- mixOmics::plotVar(PCA_whole, cutoff = 0.5, plot = FALSE) %>% 
  left_join(info_feature_complete, by = c("names" = "Feature"))

```
```{r}
b <- mixOmics::plotVar(PCA_whole, cutoff = 0.5, plot = FALSE) %>% 
  left_join(info_feature_complete, by = c("names" = "Feature"))
```

```{r}
c <- mixOmics::plotVar(PCA_whole, cutoff = 0.5, plot = FALSE) %>% 
  left_join(info_feature_complete, by = c("names" = "Feature"))
```

```{r}
ggsave("../Figures/metabolomics_Figures/PCA_plot_group_filtered.png", plot = last_plot(), dpi = 600, width = 8, height = 5, units = "in")
```

```{r}
# Assuming `data_tic_filtered` contains `SampleID` and `TIC` columns
PCA_whole_scores <- PCA_whole_scores %>%
  left_join(data_tic_filtered, by = "SampleID")  # Join TIC data by SampleID

# Plot with continuous color scale for TIC
PCA_plot <- PCA_whole_scores %>%
  #ggscatter(x = "PC1", y = "PC2", color = "TIC.x", alpha = 0.6,
  ggscatter(x = "PC1", y = "PC2", color = "TIC", alpha = 0.6,
            title = paste("PCA - TIC"),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + 
  coord_fixed() + 
  scale_color_viridis_c()  # Use continuous color scale for TIC

# Display the plot
# PCA_plot

```
```{r}
ggsave("../Figures/metabolomics_Figures/PCA_plot_TIC.png", plot = last_plot(), dpi = 600, width = 8, height = 5, units = "in")
```
```{r}
#Excluding means
i <- "host_subject_id"
j <- "category_label"

PCA_plot_2 <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, shape = j, alpha = 0.6,
            title = paste("PCA - Skin Metabolic Profiles Acne lesional and non-lesional vs Healthy "),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed()

```
```{r}
ggsave("../figures/PCA_plot_group_subjectID.png", plot = last_plot(), dpi = 600, width = 8, height = 8, units = "in")
```

```{r}
#including means 
i <- "host_subject_id"
j <- "category_label"

PCA_plot_2 <- PCA_whole_scores %>%
  ggscatter(x = "PC1", y = "PC2", color = i, shape = j, alpha = 0.6,
            title = paste("PCA - Skin Metabolic Profiles Acne lesional and non-lesional vs Healthy "),
            xlab = paste("PC1 (", round(PCA_whole$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("PC2 (", round(PCA_whole$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            ggtheme = theme_classic()) +
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(i))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) + 
  # Remove color aesthetic from the grouping mean points
  geom_point(data = PCA_whole_scores %>% group_by((!!sym(j))) %>% 
               summarise_at(vars(matches("PC")), mean), aes(PC1, PC2), size = 4, shape = 8) +  # Shape only
  theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
        axis.text = element_text(size = 4)) + coord_fixed()

```
```{r}
# PERMANOVA
# dist_metabolites <- vegdist(data_sample_clr, method = "euclidean")
# 
# disper_donor <- betadisper(dist_metabolites, PCA_whole_scores$host_subject_id)
# 
# #significant variation between the groups
# anova(disper_donor)
# permanova <- adonis2(dist_metabolites ~ PCA_whole_scores$host_subject_id + PCA_whole_scores$category_label, PCA_whole_scores, na.action = na.omit)
# 
# # Ensure `valid_rows` aligns with the row names of the metadata and data
# valid_rows <- rownames(PCA_whole_scores) %in% rownames(data_sample_clr)
# 
# # Subset the `dist_metabolites` distance matrix
# dist_matrix <- as.matrix(dist_metabolites)
# # dist_matrix <- dist_matrix[valid_rows, valid_rows] # Skip
# # dist_metabolites <- as.dist(dist_matrix)  # Convert back to a `dist` object # Skip
# 
# # Match the metadata to the distance matrix
# PCA_whole_scores <- PCA_whole_scores[rownames(dist_matrix), ]
# 
# # Check for significant dispersion
# disper_donor <- betadisper(dist_metabolites, PCA_whole_scores$host_subject_id)
# anova_disper <- anova(disper_donor)
# print(anova_disper)
# 
# # Run PERMANOVA for group-level differences
# permanova <- adonis2(
#   dist_metabolites ~ host_subject_id + category_label, 
#   data = PCA_whole_scores,
#   na.action = na.omit
# )
# print(permanova)

```

```{r}
data_sample <- data_sample_filtered

data_sample <- data_sample_method1

data_sample <- data_sample_method2
```

```{r}
# Acne_L vs Healthy
sample_LvsH <- metadata_final %>% 
  dplyr::filter(category_label == "Acne Lesional" | category_label == "Healthy")

data_LvsH <- data_sample %>% 
  dplyr::filter(SampleID %in% sample_LvsH$SampleID) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")
```

```{r}
sample_NLvsH <- metadata_final %>% 
  dplyr::filter(category_label == "Acne Non-lesional" | category_label == "Healthy")

sample_NLvsL <- metadata_final %>% 
  dplyr::filter(category_label == "Acne Non-lesional" | category_label == "Acne Lesional")

sample_LvsH <- metadata_final %>% 
  dplyr::filter(category_label == "Acne Lesional" | category_label == "Healthy")

sample_all_groups <- metadata_final %>% 
  dplyr::filter(category_label == "Acne Lesional" | category_label == "Healthy" | category_label == "Acne Non-lesional")


data_NLvsH <- data_sample %>% 
  dplyr::filter(SampleID %in% sample_NLvsH$SampleID) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")

data_NLvsL <- data_sample %>% 
  dplyr::filter(SampleID %in% sample_NLvsL$SampleID) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")

data_LvsH <- data_sample %>% 
  dplyr::filter(SampleID %in% sample_LvsH$SampleID) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")

data_all_groups <- data_sample %>% 
  dplyr::filter(SampleID %in% sample_all_groups$SampleID) %>% 
  column_to_rownames("SampleID") %>% 
  select_at(vars(-one_of(nearZeroVar(., names = TRUE)))) %>% 
  rownames_to_column("SampleID")


# RCLR transformation
data_NLvsH_clr <- decostand(data_NLvsH %>% column_to_rownames("SampleID"), method = "rclr")
data_NLvsL_clr <- decostand(data_NLvsL %>% column_to_rownames("SampleID"), method = "rclr")
data_LvsH_clr <- decostand(data_LvsH %>% column_to_rownames("SampleID"), method = "rclr")
data_all_groups_clr <- decostand(data_all_groups %>% column_to_rownames("SampleID"), method = "rclr")

```

```{r}
PCA_NLvsH <- mixOmics::pca(data_NLvsH_clr, ncomp = 2, center = TRUE, scale = TRUE)

PCA_NLvsH_scores <- data.frame(PCA_NLvsH$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

PLSDA_NLvsH <- mixOmics::plsda(data_NLvsH_clr, PCA_NLvsH_scores$category_label, ncomp = 2, scale = TRUE)

 i <- "category_label"

 PLSDA_NLvsH_plot <- PCA_NLvsH_scores %>%
   ggscatter(x = "PC1", y = "PC2", color = i, alpha = 0.6,
             title = paste("PCA - Acne Non-Lesional vs Healthy "), palette = "npg",
             xlab = paste("PC1 (", round(PCA_NLvsH$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""),
             ylab = paste("PC2 (", round(PCA_NLvsH$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
             ggtheme = theme_classic()) +
   geom_point(data = PCA_NLvsH_scores %>% group_by((!!sym(i))) %>%
                summarise_at(vars(matches("PC")), mean), aes(PC1, PC2, color = (!!sym(i))), size = 4, shape = 8) +
   theme(plot.title = element_text(size = 10), axis.title = element_text(size = 8),
         axis.text = element_text(size = 4)) + coord_fixed()
 
# Plot PLSDA for NL vs Healthy

i <- "category_label"
#"#c49c6b", "#008080"

PLSDA_NLvsH_scores <- data.frame(PLSDA_NLvsH$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

# PLSDA_NLvsH_plot <- PLSDA_NLvsH_scores %>%
#   ggscatter(x = "comp1", y = "comp2", color = "category_label", alpha = 0.6, title = "PLS-DA - Acne Non-Lesional vs Healthy", 
#             xlab = paste("Component 1 (", round(PLSDA_NLvsH$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
#             ylab = paste("Component 2 (", round(PLSDA_NLvsH$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
#             legend.title = "Cohort", ggtheme = theme_classic(), palette = c("#67b2be", "#423fa6")) +
#   geom_point(data = PLSDA_NLvsH_scores %>% group_by(category_label) %>% 
#                summarise_at(vars(matches("comp")), mean), aes(comp1, comp2, color = category_label), size = 3, shape = 8) +
#   theme(plot.title = element_text(size = 10),axis.title = element_text(size = 8),
#         axis.text = element_text(size = 5)) + coord_fixed()

PLSDA_NLvsH_plot <- PLSDA_NLvsH_scores %>%
  ggscatter(x = "comp1", y = "comp2", color = "category_label", alpha = 0.6, size = 4, title = "Acne Non-lesional vs Healthy", 
            xlab = paste("Component 1 (", round(PLSDA_NLvsH$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("Component 2 (", round(PLSDA_NLvsH$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            legend.title = "", ggtheme = theme_classic(), palette = c("#67b2be", "#423fa6")) +
  geom_point(data = PLSDA_NLvsH_scores %>% group_by(category_label) %>% 
               summarise_at(vars(matches("comp")), mean), aes(comp1, comp2, color = category_label), size = 5, shape = 8, show.legend = FALSE) +
  stat_ellipse(aes(x = comp1, y = comp2, color = category_label, fill = category_label), 
               alpha = 0.2, level = 0.95, geom = "polygon", show.legend = FALSE) +  # Add transparent ellipses
  theme(plot.title = element_text(size = 18, hjust = 0.65),
        plot.title.position = "plot",
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        panel.border = element_rect(color = "black", fill = NA, size = 1), # Add a border
        legend.position = "bottom", 
        legend.text = element_text(size = 14)) + coord_fixed() + 
  annotate("text", x = -7, y = 8.25, label = "PERMANOVA\np-val < 0.001", 
           hjust = 0.5, vjust = 0.5, size = 4, color = "black")

#Permanova 
dist_metabolites <- vegdist(data_NLvsH_clr, method = "euclidean")
disper_group <- betadisper(dist_metabolites, PCA_NLvsH_scores$category_label)
anova(disper_group)
permanova <- adonis2(dist_metabolites ~ PCA_NLvsH_scores$host_subject_id + PCA_NLvsH_scores$category_label, PCA_NLvsH_scores, na.action = na.omit)

# Save the PERMANOVA results
permanova <- adonis2(dist_metabolites ~ PCA_NLvsH_scores$host_subject_id + PCA_NLvsH_scores$category_label, 
                     data = PCA_NLvsH_scores, 
                     permutations = 9999,  # Increase permutations for accuracy
                     na.action = na.omit)

# Extract the p-value for host_subject_id
p_host_subject_id <- permanova$`Pr(>F)`[1]

# Format the p-value in scientific notation
p_value_scientific <- formatC(p_host_subject_id, format = "e", digits = 3)

# Print the formatted p-value
print(p_value_scientific)

ggsave("../Figures/metabolomics_Figures/analysis/PLSDA_plot_Acne_NLvsHealthy.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")
```

```{r}
# Plot PCA for NL vs L
PCA_NLvsL <- mixOmics::pca(data_NLvsL_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_NLvsL_scores <- data.frame(PCA_NLvsL$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

PLSDA_NLvsL <- mixOmics::plsda(data_NLvsL_clr, PCA_NLvsL_scores$category_label, ncomp = 2, scale = TRUE)

i <- "group"

# Plot PLSDA for NL vs L
PLSDA_NLvsL_scores <- data.frame(PLSDA_NLvsL$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

# PLSDA_NLvsL_plot <- PLSDA_NLvsL_scores %>%
#   ggscatter(x = "comp1", y = "comp2", color = "category_label", alpha = 0.6, title = "PLS-DA - Acne Non-Lesional vs Healthy", 
#             xlab = paste("Component 1 (", round(PLSDA_NLvsH$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
#             ylab = paste("Component 2 (", round(PLSDA_NLvsH$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
#             legend.title = "Cohort", ggtheme = theme_classic(), palette = c("#67b2be", "#423fa6")) +
#   geom_point(data = PLSDA_NLvsH_scores %>% group_by(category_label) %>% 
#                summarise_at(vars(matches("comp")), mean), aes(comp1, comp2, color = category_label), size = 3, shape = 8) +
#   theme(plot.title = element_text(size = 10),axis.title = element_text(size = 8),
#         axis.text = element_text(size = 5)) + coord_fixed()


PLSDA_NLvsL_plot <- PLSDA_NLvsL_scores %>%
  ggscatter(x = "comp1", y = "comp2", color = "category_label", alpha = 0.6, size = 4, title = "PLS-DA  Acne Lesional vs Non-lesional", 
            xlab = paste("Component 1 (", round(PLSDA_NLvsL$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("Component 2 (", round(PLSDA_NLvsL$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            legend.title = "", ggtheme = theme_classic(), palette = c("#df7963", "#67b2be")) +
  geom_point(data = PLSDA_NLvsL_scores %>% group_by(category_label) %>% 
               summarise_at(vars(matches("comp")), mean), aes(comp1, comp2, color = category_label), size = 5, shape = 8, show.legend = FALSE) +
  stat_ellipse(aes(x = comp1, y = comp2, color = category_label, fill = category_label), 
               alpha = 0.2, level = 0.95, geom = "polygon", show.legend = FALSE) +  # Add transparent ellipses
  theme(plot.title = element_text(size = 18, hjust = 0.65),
        plot.title.position = "plot",
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        legend.position = "bottom") +  # Add full border
  coord_fixed() +
  annotate("text", x = -8.5, y = 7, label = "PERMANOVA\np-val < 0.001", 
           hjust = 0.5, vjust = 0.5, size = 4, color = "black") # Add annotation


ggsave("../Figures/metabolomics_Figures/analysis/PLSDA_plot_Acne_NLvsL.png", plot = last_plot(), dpi = 600, width = 8, height = 6, units = "in")

#Permanova 
dist_metabolites <- vegdist(data_NLvsL_clr, method = "euclidean")
disper_group <- betadisper(dist_metabolites, PLSDA_NLvsL_scores$category_label)
anova(disper_group)
permanova <- adonis2(dist_metabolites ~ PLSDA_NLvsL_scores$host_subject_id + PLSDA_NLvsL_scores$category_label, PLSDA_NLvsL_scores, na.action = na.omit)

# Save the PERMANOVA results
permanova <- adonis2(dist_metabolites ~ PLSDA_NLvsL_scores$host_subject_id + PLSDA_NLvsL_scores$category_label, 
                     data = PLSDA_NLvsL_scores, 
                     permutations = 9999,  # Increase permutations for accuracy
                     na.action = na.omit)

# Extract the p-value for host_subject_id
p_host_subject_id <- permanova$`Pr(>F)`[1]

# Format the p-value in scientific notation
p_value_scientific <- formatC(p_host_subject_id, format = "e", digits = 3)

# Print the formatted p-value
print(p_value_scientific)
```
```{r}
# Plot PCA V vs Healthy
# Perform PCA for L vs H
PCA_LvsH <- mixOmics::pca(data_LvsH_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_LvsH_scores <- data.frame(PCA_LvsH$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

# Perform PLS-DA for L vs H
PLSDA_LvsH <- mixOmics::plsda(data_LvsH_clr, as.factor(PCA_LvsH_scores$category_label), ncomp = 2, scale = TRUE)

# Extract PLS-DA scores for L vs H
PLSDA_LvsH_scores <- data.frame(PLSDA_LvsH$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

# Plot PLS-DA for L vs H
PLSDA_LvsH_plot <- PLSDA_LvsH_scores %>%
  ggscatter(x = "comp1", y = "comp2", color = "category_label", alpha = 0.6, size = 4, title = "PLS-DA Healthy vs Acne Lesional", 
            xlab = paste("Component 1 (", round(PLSDA_LvsH$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("Component 2 (", round(PLSDA_LvsH$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            legend.title = "", ggtheme = theme_classic(), palette = c("#df7963", "#423fa6")) +
  geom_point(data = PLSDA_LvsH_scores %>% group_by(category_label) %>% 
               summarise_at(vars(matches("comp")), mean), aes(comp1, comp2, color = category_label), size = 5, shape = 8, show.legend = FALSE) +
  stat_ellipse(aes(x = comp1, y = comp2, color = category_label, fill = category_label), 
               alpha = 0.2, level = 0.95, geom = "polygon", show.legend = FALSE) +  # Add transparent ellipses
  theme(plot.title = element_text(size = 18, hjust = 0.65),
        plot.title.position = "plot",
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14),
        panel.border = element_rect(color = "black", fill = NA, size = 1),
        legend.position = "bottom") +  # Move the legend to the bottom
  coord_fixed() + 
  annotate("text", x = -3.2, y = 8.6, label = "PERMANOVA\np-val < 0.001", 
           hjust = 0.5, vjust = 0.5, size = 4, color = "black")  # Add annotation


# Save the PLS-DA plot for L vs H
ggsave("../Figures/metabolomics_Figures/analysis/PLSDA_plot_Acne_LvsH.png", plot = PLSDA_LvsH_plot, dpi = 600, width = 8, height = 6, units = "in")

# PERMANOVA for L vs H
dist_metabolites <- vegdist(data_LvsH_clr, method = "euclidean")
disper_group <- betadisper(dist_metabolites, PCA_LvsH_scores$category_label)
anova(disper_group)

# Run PERMANOVA for group differences
permanova <- adonis2(dist_metabolites ~ PCA_LvsH_scores$host_subject_id + PCA_LvsH_scores$category_label, 
                     data = PCA_LvsH_scores, 
                     permutations = 9999,  # Increase permutations for accuracy
                     na.action = na.omit)

# Extract the p-value for host_subject_id
p_host_subject_id <- permanova$`Pr(>F)`[1]

# Format the p-value in scientific notation
p_value_scientific <- formatC(p_host_subject_id, format = "e", digits = 3)

# Print the formatted p-value
print(p_value_scientific)

```
```{r}
# Load the patchwork package
library(patchwork)

# Combine the three plots
combined_plot <- PLSDA_NLvsH_plot + PLSDA_NLvsL_plot + PLSDA_LvsH_plot + 
  plot_layout(ncol = 3, guides = "collect") & 
  theme(legend.position = "bottom", legend.title = element_blank())

# Save the combined plot as an SVG
ggsave("../Figures/metabolomics_Figures/analysis/PLSDA_combined_plot.svg", 
       plot = combined_plot, dpi = 600, width = 24, height = 8, units = "in")

```

```{r}
apply_rclr <- function(data) {
  # Apply robust CLR transformation
  data_clr <- decostand(data, method = "rclr")
  
  # Remove zero-variance columns
  zero_var_cols <- which(apply(data_clr, 2, var) == 0)
  if (length(zero_var_cols) > 0) {
    data_clr <- data_clr[, -zero_var_cols]
  }
  return(data_clr)
}
```


```{r}
# Run for all 3 groups

PCA_all_groups <- mixOmics::pca(data_all_groups_clr, ncomp = 2, center = TRUE, scale = TRUE)
PCA_all_groups_scores <- data.frame(PCA_all_groups$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

# Perform PLS-DA
PLSDA_all_groups <- mixOmics::plsda(data_all_groups_clr, as.factor(PCA_all_groups_scores$category_label), ncomp = 2, scale = TRUE)

# Extract PLS-DA scores
PLSDA_all_groups_scores <- data.frame(PLSDA_all_groups$variates$X) %>% 
  rownames_to_column("SampleID") %>% left_join(metadata_final)

# Plot PLS-DA for L vs H
PLSDA_all_groups_plot <- PLSDA_all_groups_scores %>%
  ggscatter(x = "comp1", y = "comp2", color = "category_label", alpha = 0.6, size = 4, title = "PLS-DA: Lesional vs Healthy", 
            xlab = paste("Component 1 (", round(PLSDA_all_groups$prop_expl_var$X[1]*100, digits = 1),"%)", sep = ""), 
            ylab = paste("Component 2 (", round(PLSDA_all_groups$prop_expl_var$X[2]*100, digits = 1),"%)", sep = ""),
            legend.title = "", ggtheme = theme_classic(), palette = c("#df7963", "#423fa6", "#67b2be")) +
  geom_point(data = PLSDA_all_groups_scores %>% group_by(category_label) %>% 
               summarise_at(vars(matches("comp")), mean), aes(comp1, comp2, color = category_label), size = 5, shape = 8, show.legend = FALSE) +
  stat_ellipse(aes(x = comp1, y = comp2, color = category_label, fill = category_label), 
               alpha = 0.2, level = 0.95, geom = "polygon", show.legend = FALSE) +  # Add transparent ellipses
  theme(plot.title = element_text(size = 18, hjust = 0.7),
        plot.title.position = "plot",
        axis.title = element_text(size = 14),
        axis.text = element_text(size = 14),
        legend.text = element_text(size = 14)) + 
  coord_fixed() +
  annotate("text", x = -13, y = 17, label = "PERMANOVA\np-val < 0.001", 
           hjust = 0.5, vjust = 0.5, size = 4, color = "black")  # Add annotation

# Save the PLS-DA plot for L vs H
ggsave("../Figures/metabolomics_Figures/analysis/PLSDA_plot_all_groups.png", plot = PLSDA_all_groups_plot, dpi = 600, width = 8, height = 6, units = "in")

# PERMANOVA for L vs H
dist_metabolites <- vegdist(data_all_groups_clr, method = "euclidean")
disper_group <- betadisper(dist_metabolites, PCA_all_groups_scores$category_label)
anova(disper_group)

# Run PERMANOVA for group differences
permanova <- adonis2(dist_metabolites ~ PCA_all_groups_scores$host_subject_id + PCA_all_groups_scores$category_label, 
                     data = PCA_all_groups_scores, 
                     permutations = 9999,  # Increase permutations for accuracy
                     na.action = na.omit)

# Extract the p-value for host_subject_id
p_host_subject_id <- permanova$`Pr(>F)`[1]

# Format the p-value in scientific notation
p_value_scientific <- formatC(p_host_subject_id, format = "e", digits = 3)

# Print the formatted p-value
print(p_value_scientific)


```

